name: Karma Tests

# Run on Pull Request to master only
on:
  pull_request:
    branches: [ master ]
  push: 
    branches: [ master ]

# Job Setup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 #Checkout Repo
    - uses: actions/setup-node@v1 #Setup Node
      with:
        node-version: '12'
    - name: Run Karma Tests
      run: |
        npm install
        npm run test:ci